CREATE TABLE IF NOT EXISTS member (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    real_name VARCHAR(50),
    birth INTEGER,
    born VARCHAR(20),
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS valorant (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    member_id INTEGER NOT NULL,
    ingame_name VARCHAR(40),
    image VARCHAR(30),
    role VARCHAR(30),
    nationality VARCHAR(30),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `fk_valorant_member` FOREIGN KEY(member_id) REFERENCES member(id)
);

CREATE TABLE IF NOT EXISTS genshin_impact (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    member_id INTEGER NOT NULL,
    ingame_name VARCHAR(40),
    image VARCHAR(30),
    nationality VARCHAR(30),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `fk_genshin_impact_member` FOREIGN KEY(member_id) REFERENCES member(id)
);

CREATE TABLE IF NOT EXISTS fortnite (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    member_id INTEGER NOT NULL,
    ingame_name VARCHAR(40),
    image VARCHAR(30),
    nationality VARCHAR(30),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `fk_fortnite_member` FOREIGN KEY(member_id) REFERENCES member(id)
);

CREATE TABLE IF NOT EXISTS apex_legends (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    member_id INTEGER NOT NULL,
    ingame_name VARCHAR(40),
    image VARCHAR(30),
    nationality VARCHAR(30),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `fk_apex_legends_member` FOREIGN KEY(member_id) REFERENCES member(id)
);

CREATE TABLE IF NOT EXISTS mobile_legends (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    member_id INTEGER NOT NULL,
    ingame_name VARCHAR(40),
    image VARCHAR(30),
    role VARCHAR(30),
    nationality VARCHAR(30),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `fk_mobile_legends_member` FOREIGN KEY(member_id) REFERENCES member(id)
);

CREATE TABLE IF NOT EXISTS dota2 (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    member_id INTEGER NOT NULL,
    ingame_name VARCHAR(40),
    image VARCHAR(30),
    role VARCHAR(30),
    nationality VARCHAR(30),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `fk_dota2_member` FOREIGN KEY(member_id) REFERENCES member(id)
);

CREATE TABLE IF NOT EXISTS the_forest (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    member_id INTEGER NOT NULL,
    ingame_name VARCHAR(40),
    image VARCHAR(30),
    nationality VARCHAR(30),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `fk_the_forest_member` FOREIGN KEY(member_id) REFERENCES member(id)
);